name: Close PR

on:
  pull_request_target:
    types:
      - opened

jobs:
  close-pr:
    name: Close PR
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub CLI
        run: gh pr close "$number" --repo "$repo" --comment "$comment"
        env:
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
          comment: "Thank you for your pull request. Because `${{ github.repository }}` is a read-only subtree split of `salient-labs/toolkit`, it has been closed automatically. Please create a PR on https://github.com/salient-labs/toolkit instead."
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
